[project]
name = "lab-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "pandas>=1.1.5",
    "streamlit>=1.23.1",
]
